services:
  postgres-event:
    image: postgres:16-alpine
    container_name: postgres-event
    environment:
      POSTGRES_DB: event_db
      POSTGRES_USER: event
      POSTGRES_PASSWORD: event
    ports:
      - "5433:5432"
    volumes:
      - postgres-event-data:/var/lib/postgresql/data
    networks:
      - ticket-booking-net

  postgres-booking:
    image: postgres:16-alpine
    container_name: postgres-booking
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking
      POSTGRES_PASSWORD: booking
    ports:
      - "5434:5432"
    volumes:
      - postgres-booking-data:/var/lib/postgresql/data
    networks:
      - ticket-booking-net

  postgres-payment:
    image: postgres:16-alpine
    container_name: postgres-payment
    environment:
      POSTGRES_DB: payment_db
      POSTGRES_USER: payment
      POSTGRES_PASSWORD: payment
    ports:
      - "5435:5432"
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data
    networks:
      - ticket-booking-net

  postgres-user:
    image: postgres:16-alpine
    container_name: postgres-user
    environment:
      POSTGRES_DB: user_db
      POSTGRES_USER: appuser
      POSTGRES_PASSWORD: appuser
    ports:
      - "5436:5432"
    volumes:
      - postgres-user-data:/var/lib/postgresql/data
    networks:
      - ticket-booking-net

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - ticket-booking-net

  zookeeper:
    image: confluentinc/cp-zookeeper:7.6.1
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"
    networks:
      - ticket-booking-net

  kafka:
    image: confluentinc/cp-kafka:7.6.1
    container_name: kafka
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
    ports:
      - "9092:9092"
    networks:
      - ticket-booking-net

volumes:
  postgres-event-data:
  postgres-booking-data:
  postgres-payment-data:
  postgres-user-data:

networks:
  ticket-booking-net:
    driver: bridge
