server:
  port: 8081

spring:
  application:
    name: event-service
  datasource:
    url: jdbc:postgresql://localhost:5432/event_db
    username: event
    password: event
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: false

management:
  endpoint:
    health:
      show-details: never
